[#characters]
= Creating a character

== Choose a name

== Choose a fighting style

== Choose a description
I highly recommend you draw a picture, even if you think your drawing skills suck.

== Choose a belief
Should be something the GM can actively challenge with hard choices.
Shouldn't completely piss off the other players, if there's disagreement, players decide.

== Choose a flaw
Should be something you are actively interested in using to get your character into trouble.
Shouldn't completely piss off the other players, if there's disagreement, players decide.

== Choose a goal
Should be something potentially, but not trivially, achievable within one game session. If there's disagreement, GM decides.
Can wait until the end of the first session.

[NOTE]
====
Beliefs, flaws, and goals aren't just filler to be forgotten about. You cannot level up without playing them.
====

== Choose backgrounds
Distribute 3 points between backgrounds of your choice, no more than 2 in any one.
Can wait until during play.

Backgrounds are used to overcome problems, and are up to you.
Be as creative as you like, whether that's "former cop" or "calligraphy instructor to the Prince in Exile of Xaran".

== Choose energy
Distribute 10 points among Defense ◯ ,  Grapple ▧ , and Attack ⬟ .
Don't worry about min-maxing, just go with what makes sense for your character concept.
If you're really concerned about it, put 4 in Attack ⬟, 3 in Defense ◯, 2 in Grapple ▧, and the last point wherever.

== Choose moves
You know a Defense, ◯ ☵, a Grapple, ▧ ☵, and an Attack, ⬟ ☵. Make up cool names for them.
Don't worry too much about what the symbols mean.

If you're still concerned about it, read the <<conflict>> and <<turns>> chapter.
