[#intro]
= Intro

== Why roleplaying games?

Unlike almost any other activity, roleplaying games combine:

* Playing a role: portraying a character in a collaborative story with other people
* Playing a game: making choices constrained by rules in pursuit of a goal

== Why this game?

This game puts player choice first.
When there's uncertainty about an outcome, players make simultaneous choices from clearly ranked options to find out what happens.
Success or failure is up to the choices you make during play, not the luck of the dice or a "bad" choice during character creation.

== Materials

* Pencils
* Paper
* Printouts of the character sheet at the end of the book, or more blank paper
* Printouts of the cards accompanying this book, or index cards to write on
* Three different kinds of tokens.  You can use coins, cubes, beads or whatever you have, as long as they're visibly different and you can conceal several of them in your hand.  You'll need at least 10 per player.

== Participants

You need 2-5 people. One person is the Game Moderator (GM), the other players each create and control a Player Character (PC).

Players make decisions for their PCs. The GM is responsible for making decisions for all Non-Player Characters (NPCs). The GM isn't the author of the story, but they keep the story interesting by challenging the players with <<countdowns.adoc#countdowns>>, <<problems.adoc#problems>>, and <<conflict.adoc#conflict>>.
