[#levelup]
= Level Up

At the end of a session, ask the following questions for each player:

* Did you play out a problem with complications or failure based on your *belief* or *flaw*?
* Did you accomplish your *goal*?
* Did you reach zero energy in at least one type of action during a *conflict*?

The answers should have already been clearly marked during play, but if there is disagreement, the GM decides.

Yes marks in all three categories mean you can level up. Increment your level by one.

When you level up, choose *one* of:

* Learn a move.
* Once you have learned all the moves, you can learn a variant of an existing move. Choose either +1 multiplier and -1 base or -1 multiplier and +1 base compared to the existing move. You can learn up to two moves this way, and they cannot copy the same move. You may spend a level up to replace one of the variants you know with a different move. Variants are considered the same as the original move for combos.
* Learn or make changes to two combo followups. You're limited to two followups per starting move. You must already know the followup moves. You don't need to know the starting move as long as one of your allies does.
* Add one to your maximum energy for one type of action. It must be a type that reached zero during a conflict.
* Learn a special. You cannot learn multiple copies of the exact same special, e.g. if you know Wax On (Defend) you can learn Wax On (Attack), but not another copy of Wax On (Defend).

When you level up, *also* choose *one* of:

* Regain up to 3 background points. You can have at most 3 total.
* Regain up to 1 veto. You can have at most 1 total.

Once you level up, erase the following marks:

* Erase your goal and its mark.
* Erase all marks for reaching zero energy. This means you can't save marks for types you didn't choose to increase.
* Erase marks for your belief and flaw only if *both* are marked. This means you can't always use one of them to level up, you have to play them equally.

Make sure to choose a name for any moves you learn. If you want to change the name of a move you already know, you can do so for free.

If you do not level up, you can save yes marks for the next session, but cannot have multiple marks per question.

You can adjust goals, beliefs, and flaws at the end of a session even if you did not level up.
Choose a new goal, either now, or before the beginning of the next session.
If you think that your character's beliefs or flaws have meaningfully changed, you may rewrite them.
The same caveats from character creation regarding goals, beliefs, and flaws apply.

You can change backgrounds with GM approval, but it should be rare.

== Replacement characters

If the replacement for a dead character continues the deceased's fighting tradition, they can start at a level up to 5 or the deceased's level, whichever is lower.

Choose energy and starting moves as for a level 1 character, then make decisions for each level up.
The level ups can involve learning a move or combo known by the deceased, but not a special.

