[#levelup]
= Leveling up

At the end of a session, ask the following questions for each player:

* Did you play out a problem with complications or failure based on your belief or flaw?
* Did you accomplish your goal?
* Did you reach zero energy in at least one type of action in a conflict?

The answers should have already been clearly marked during play, but if there is disagreement, the GM decides.

Yes answers to all three questions mean you can level up. Increment your level by one.

When you level up, choose one of:

* Learn a move. See <<five elements>> below for restrictions.
* Learn one combo followup move, or change an existing one. You're limited to two followups per starting move.
* Add one to your maximum energy for one type of action.
* Learn a special.

When you level up, also choose one of:

* Refill up to 3 background points.
* Refill up to 1 veto.

Make sure to choose a name for any moves you learn.
You cannot learn more than one copy of the same move or special; if you just want to change the name, you can do so for free.

If you do not level up, you can save yes marks for the next session, but can have a maximum of one per question.
Once you level up, erase all yes marks.

Choose a new goal, either now, or before the beginning of the next session.
If there's a disagreement, GM decides.

If you think that your character's beliefs or flaws have meaningfully changed, you may rewrite them.
If there's a disagreement, players decide.

== Five elements
After you have learned all the moves using the three elements ☷ ☵ ☲ , you can learn moves using the fourth and fifth elements ☰ ☯:

include::5elements.adoc[]

include::moves.adoc[]

[#replacement characters]
== Replacement characters

If the replacement for a dead character continues the deceased's fighting tradition, they can start at a level up to 5 or the deceased's level, whichever is lower.

Choose energy and starting moves as for a level 0 character, then make decisions for each level up.
The level ups can involve learning a move or combo known by the deceased, but not a special.

