[#specials]
= Specials

Specials can be used to modify the rules in different ways.
Once a special is used, it cannot be used again until after a full rest.
Each character can use at most one special per conflict turn.

The description of a special identifies at what time in a turn it can be used.

To use a special, play its card face down at the appropriate time.
Before revealing it, give your opponent an opportunity to play a special of their own.
If a special should be revealed at a time different from when it is used, the description will say so.

Some specials have requirements that must be met before learning, either in terms of character level reached, or specials learned first. 

Some specials have multiple variations, each specific to a particular action type.
For instance, Wax On  Attack  is different from Wax On  Defend  .
Each variation must be learned separately and counts as a separate special.

If specials clash in regards to timing or effect, the player of the special closer to the bottom of the list below decides the outcome.
If identical specials clash, neither takes effect.
If there is still a question, the GM decides.

.Example clash between specials
****
You play Pressure Point, another player plays Yojimbo. There's a dispute about whether you get to choose where losses are distributed. Yojimbo is after Pressure Point on the list, so the player of Yojimbo decides that your choice of location takes effect on the original opponent, but not on the character that ends up taking the loss.

You play Scouter, your opponent plays Way of the Samurai. Even though Way of the Samurai is lower on the list, there is no interaction between the two specials, so your opponent cannot decide the outcome of Scouter. 
****

[NOTE]
====
You are welcome to re-theme specials to be more appropriate for your character. For instance, if your character suffering from a hangover isn't funny to you, Drunken Monkey could just as easily be a helpful but capricious spirit.
====

<<<
== Scouter
* Use before choosing an opponent, or before choosing a stance.
* One opponent's moves, combos, and specials are public knowledge for the rest of the conflict.

== To Blave
* Use at any time matching another special you know.
* Can be used twice per conflict instead of once per full rest.
* Has no other effect.

== There Can Be Only One
* Use before choosing an opponent, or before choosing a stance.
* Choose a character. You and that character cannot choose a different opponent until one of you is out of the conflict.
* Either of you can respond to opponents choosing you as normal.

== Pressure Point
* Use before choosing a move.
* Reveal before resolving the turn.
* You choose where your opponent's losses are distributed this turn.

== Wax On  (Defend / Grapple / Attack)
* Use before choosing a move.
* Reveal before resolving the turn.
* If the type of your opponent's action matches this special, you lose no energy from their stance this turn.

== Santa Carla   (Defend / Grapple / Attack)
* Requires: Level 5
* Use before choosing a move.
* Reveal before resolving the turn
* If the type of your stance and action matches this special and you win, regain energy equal to the amount you committed to the stance this turn.
* Do not multiply the gain by your move's stance multiplier.
* You choose where to distribute the gain, but you cannot regain more than your maximum.

== Dig Two Graves (Defend / Grapple / Attack)
* Requires: Level 5 and Wax On of the matching type.
* Use before choosing a move.
* Reveal before resolving the turn.
* If the type of your opponent's action matches this special, they lose energy equal to the amount you lose this turn.

== Predictabo! (Defend / Grapple / Attack)
* Requires: Level 10
* Use before choosing a stance.
* For this turn your opponent cannot choose a move with an action matching this special.

== Yojimbo
* Requires: Level 5
* Use before resolving a different character's turn.
* This turn you lose the amount of energy they would have lost, and they lose 0.
* Does not count against your limit of one special per turn.


== Liquid Metal
* Requires: Level 10
* Duplicate the effect of a special that has been used by a different character in this conflict.
* Use and reveal at the time appropriate for the duplicated special.
* Cannot duplicate specials after it on the list.

== Drunken Monkey
* Requires: Level 10
* Use before choosing a move.
* Until this conflict ends, once per turn after revealing your move, you can choose to replace it.
* Your opponent selects the replacement randomly from your remaining moves (not including surrender).
* You cannot participate in the next conflict, even if you rest first. 

== The Way of the Samurai
* Requires: Level 10
* Use before choosing a stance.
* Regain energy up to your maximum in all types.
* You cannot be removed from this conflict until it ends, even if you reach 0 total energy.
* At the end of the conflict, you die irrevocably.
* Play out the conflict; even if the outcome is inevitable, the fate of your allies is not.
* NPCs cannot use this special, for obvious reasons.
