[#specials]
= Specials

Specials can be used to modify the rules in different ways.
Once a special is used, it cannot be used again until after resting.
Each character can use at most one special per turn.

The description of a special identifies at what time in a turn it can be used.
To use a special, play its card face down at the appropriate time.
Before revealing it, give your opponent an opportunity to play a special of their own.
If a special should be revealed at a time different from when it is used, the description will say so.

Some specials have requirements that must be met before learning, either in terms of character level reached, or specials learned first. 

Some specials have multiple variations, each specific to a particular action type.
For instance, Parry ⬟ is different from Parry ◯ .
Each variation must be learned separately and counts as a separate special.

If specials conflict in regards to timing or effect, the player of the special closer to the bottom of the list below decides the outcome.
If identical specials conflict, neither takes effect.
If there is still a question, the GM decides.

[NOTE]
====
You are welcome to re-theme specials to be more appropriate for your character. For instance, if your character suffering from a hangover isn't funny to you, Drunken Monkey could just as easily be a helpful but capricious spirit.
====


== Insight
* Use before choosing an opponent, or before choosing a stance.
* Learn the moves, combos, and specials available to your opponent.

== Showdown
* Use before choosing an opponent, or before choosing a stance.
* Choose a character. You and that character must choose each other as opponents until one of you is out of the conflict.
* Either of you can respond to opponents choosing you as normal.

== Precise
* Use before choosing a move.
* Reveal before resolving the turn.
* You choose where your opponents losses are distributed this turn.

== Parry ◯  / ▧  / ⬟
* Use before choosing a move.
* Reveal before resolving the turn.
* If the type of your opponent's action matches this special, you lose no energy this turn.

== Vampire  ◯  / ▧  / ⬟
* Requires: Level 5
* Use before choosing a move.
* Reveal before resolving the turn
* If the type of your action matches this special, regain energy equal to the amount your opponent loses this turn.
* You choose where to distribute the gain, but you cannot regain more than your maximum.

== Dig Two Graves ◯  / ▧  / ⬟
* Requires: Level 5 and Parry of the matching type.
* Use before choosing a move.
* Reveal before resolving the turn.
* If the type of your opponent's action matches this special, they lose energy equal to the amount you lose this turn.

== Premonition ◯  / ▧  / ⬟
* Requires: Level 10
* Use before choosing a stance.
* For this turn your opponent may not choose a move with an action matching this special.

== Bodyguard
* Requires: Level 5
* Use before resolving a different character's turn.
* Does not count against your limit of one special per turn.
* Choose a character. This turn you lose energy equal to the amount they would have lost, while they lose zero.

== Mimic
* Requires: Level 10
* Duplicate the effect of a special that has been used by a different character in this conflict.
* Use and reveal at the time appropriate for the mimicked special.
* Cannot duplicate specials after it on the list.

== Drunken Monkey
* Requires: Level 10
* Use before choosing a move.
* Until this conflict ends, once per turn after revealing a move, you can replace your move with one chosen randomly by your opponent from your remaining moves.
* You may not participate in the next conflict, even if you rest first. 

== Last Stand
* Requires: Level 10
* Use before choosing a stance.
* Regain energy up to your maximum.
* You cannot be removed from this conflict until it ends, even if you reach zero total energy.
* At the end of the conflict, you die irrevocably.
* Play out the conflict; even if the outcome is inevitable, the fate of your allies is not.
* NPCs cannot use Last Stand, for obvious reasons.
