[#turns]
= Conflict Turns

To play out a conflict turn:

. Choose an opponent.
. Choose a stance, then reveal.
. Choose a move, then reveal.
. Identify the winner based on move and disadvantage.
. Resolve the consequences based on move, stance, disadvantage, and combos

== Ranking of actions
Actions represent *how* a move tries to beat an opponent. Defend blocks Attack, Grapple grabs Defend, Attack hurts attempts to Grapple.  There is no "best" action, each of them can be beaten by the appropriate choice.

include::actions.adoc[]

== Ranking of locations
Locations represent *where* on an opponent a move is aimed. Low ducks High, Mid crushes Low, High out-ranges Mid. Again, there is no "best" location, each of them can be beaten by the appropriate choice.

include::3locations.adoc[]

[NOTE]
====
If you need a mnemonic, both actions and locations happen to be ranked in alphabetical order.  G beats D beats A.  H beats M beats L.
====

== Choose an opponent

If it's your turn, choose any character on the opposing side. There are no rules for range or cover, assume you can reach any character in the conflict.

If it's not your turn and the opposing side chooses you, the rest of the rules for this turn apply symmetrically to you. Being able to choose an opponent is a tactical advantage, but it doesn't determine whether you win or lose the turn.

== Choose a stance

Stances represent preparing to take a particular action.  They make your actions more effective, but your opponent can see your stance before you choose a move.

To choose a stance, select a number between zero and your current energy corresponding to one type of action.


* If you choose a move corresponding to your stance and win, you keep the energy you committed. Your opponent will lose an amount equal to the energy you committed times a multiplier associated with your move.
* If you choose a move corresponding to your stance and lose, you will lose the energy you committed, but it is not multiplied.
* If you choose a different move, the stance was a feint, and has no effect on either side's losses. You did not commit the energy, you keep it, although it may still be reduced by other losses.

Remaining energy is public information, but conceal your total amount while selecting a stance so that you do not give away your choice before revealing.
Hold out an unambiguous fist containing the number of tokens corresponding to your choice of stance. Open your hand once both sides are ready to reveal.
Use an empty fist to indicate no stance.

.Example of choosing a stance
****
You have 3 remaining energy in Attack, and choose 2 Attack for your stance.

* If you play an Attack move and win, your opponent will lose energy equal to 2 times a multiplier.
* If you play an Attack move and lose, you will lose the 2 Attack energy.
* If you play a Defend or Grapple move, your stance will not affect losses to either side, but your 3 remaining Attack energy may be reduced by other losses. 
****

== Choose a move

Choose a move by playing the corresponding card face down, then flipping to reveal once both sides are ready.

Your most important move is surrender. If you play surrender, you are out of the conflict, and will eventually take your side's consequences of winning or losing the overall conflict, but do not suffer any energy losses for this turn. Surrender is not retreat; if you surrender in a lethal conflict your opponent can choose to kill your character immediately. If for some reason you have no other remaining moves, you must play surrender.

Other moves are defined by the name you chose, an action, a location, a multiplier applied to the amount of stance energy you committed, and a base energy loss your opponent will suffer if you win.

include::moves.adoc[]

When choosing a move, it is important to consider your potential disadvantage and combos.

== Disadvantage

If you lost your prior turn, and then play a move that matches the action *or* the location of your most recent losing move, it is at a disadvantage. If you lose, you will lose additional energy; you will also lose what otherwise would have been a tie.

Energy losses from disadvantage are cumulative with consecutive disadvantaged turns, at one point of energy per prior turn.
Disadvantage ends once you end a turn without losing, play a move that doesn't match, or at the end of the conflict.
It does not end once someone else is selected as an opponent, so leave your played move cards out face up to indicate disadvantage.
This does restrict your available moves.

.Example disadvantage
****
The prior turn you played Attack Low and lost, so that card is face up in front of you.
You play Defend Low, which contains Low, so it is at disadvantage. You lose, and lose an additional point of energy. You keep Attack Low and Defend Low face up in front of you.

The next turn, you play Attack High, which does not match Defend Low, so it is not at disadvantage. You lose, but do not lose additional energy from disadvantage. You keep Attack High face up in front of you, and return Attack Low and Defend Low to your available moves.
****

== Combos

Combos are relationships between moves that are learned separately from moves.
If the immediately prior turn was a loss for your opponent, check if the move that won is related to a combo followup that you know.
The relation is based solely on the action and location of the moves.
If you chose a move that is a combo followup and win, your opponent will lose additional energy.
Combos do not affect ties.

Combo bonuses are cumulative with consecutive combo turns, at one point of energy per prior turn.
Leave your played cards out face up in front of your opponent to indicate a combo.
This does restrict your available moves.
A player can voluntarily end the combo before choosing a move in order to return all the moves to availability.
Combos end once you lose a turn, play a move that doesn't combo, choose a different opponent, or at the end of the conflict.

You can play up to 3 consecutive winning turns to continue a combo, then must pass.
This counts as one turn for purposes of players taking equal number of turns.
The character you pass to can continue the combo against the same opponent if possible.

.Example combo
****
You have played 2 consecutive winning turns, Attack Low then Grapple High.
Your possible combo followups from Grapple High are Defend High or Attack High. You play Attack High and win. Your opponent loses an additional 2 points of energy.
Leave Attack Low, Grapple High and Attack High face up in front of your opponent. You have played 3 consecutive turns, so you pass to another player on your side. If they know a followup to Attack High, they can continue the combo.
****

[NOTE]
====
Keep your face-up disadvantage cards closer to you than the cards for combos being played against you. Because combos end as soon as a different opponent is chosen, unlike disadvantage, it should be clear from context which is which.
====

== Identify the winner

Check in order:

. If a move's action beats the other move's action, it wins.
. If a move's location beats the other move's location, it wins.
. If one move is disadvantaged, it loses.
. Otherwise it's a tie.

.Example winner
****
* You play Attack High, your opponent plays Grapple Low . Attack beats Grapple, you win.
* You play Attack High, your opponent plays Attack Low . Low beats High, you lose.
* You lost your prior turn with Defend High, your opponent won their prior turn. You play Attack High at disadvantage, your opponent plays Attack High, you lose.
****

== Resolve the consequences

In a tie, each character loses energy equal to the base amount for the other character's move, but no additional losses.
Ties end combos and disadvantage.

.Example consequences of tie
****
You play Attack High, your opponent plays Attack High . Neither of you were at disadvantage, so it's a tie. You each lose 3 energy. No cards remain face up to indicate combo or disadvantage.
****

If you played the winning move, the opponent loses energy equal to the sum of:

* (your committed stance energy times the multiplier of your move)
* their committed stance energy, without a multiplier
* the base amount of your move
* one point per prior win in your successful combo
* one point per prior loss in their disadvantage

When you commit stance energy and lose, that portion of the loss comes from the type you committed. For remaining losses, the person controlling the character that lost energy decides how to distribute it among the different types.

.Example consequences of a win
****

* The prior turn your opponent played Attack Low and lost.
* This turn, your possible combo followups are Grapple High or Attack High.
* You choose 3 Grapple for your stance, your opponent chooses 1 Defend.
* You choose Grapple High for your move, your opponent chooses Defend Low.

Since Grapple beats Defend, you win. Your opponent loses a total of 13 energy:

* 3 times 2 because your stance matched your action
* 1 because their stance matched their action
* 4 due to the base amount of your move
* 1 due to your combo
* 1 due to their disadvantage

At least 1 point of those losses is applied to Defend and the remainder according to your opponent's choice.
****

You can keep track of energy losses during a conflict by removing the corresponding tokens. Make sure to write down your current energy on your character sheet after the conflict ends.

If you reach zero energy for one action type, mark it on your character sheet for purposes of <<levelup.adoc#levelup>>. This does not restrict your ability to play moves of that type, only your ability to choose a stance of that type.

If you reach zero energy in all action types, you are out of the conflict, and suffer the consequence specified by the stakes.
In particular, if it is a lethal conflict, your character is dead, even if your side wins the overall conflict.
