[#turns]
= Conflict Turns

To play out a conflict turn:

. Choose an opponent.
. Choose a stance, then reveal.
. Choose a move, then reveal.
. Identify the winner based on move and disadvantage.
. Resolve the consequences based on move, stance, disadvantage, and combos

== Ranking of actions
Actions represent the basic objective of a move or stance. Defend blocks attacks; grapple grabs defenders; attack hurts attempts to grapple.  There is no "best" action, each of them can be beaten by the appropriate choice.

include::actions.adoc[]

[NOTE]
====
For a mnemonic, the number of sides ◯ 1 < ▧ 4 < ⬟ 5.  AttACK rhymes with blACK, defend is round like a shield.
====


== Ranking of elements
Elements represent additional detail of a move. Earth can't be burned by fire, water floods earth, fire boils water.  Or if you prefer more mundane meanings, low ducks high, mid crushes low, high out-ranges mid.

include::3elements.adoc[]
[NOTE]
====
For a mnemonic, the number of unbroken lines ☷ 0 < ☵ 1 < ☲ 2.
If you don't want to play with elements for your first couple of games, that's fine.
Ignore any mention of them and the basic mechanics will still work.
====

Once your character has leveled up and learned all of the 3-element moves, 2 more elements are available.  Their ranking is:

include::5elements.adoc[]

Jump beats low and spin, spin beats high and mid, etc.  Note that there still isn't a "best" element, both jump and spin can be beaten by an appropriate choice from just low, mid, or high.

== Choose an opponent

If it's your turn, choose any character on the opposing side. There are no rules for range or cover, assume you can reach any character in the conflict.

If it's not your turn and the opposing side chooses you, the rest of the rules for this turn apply symmetrically to you. Being able to choose an opponent is a tactical advantage, but it doesn't determine whether you win or lose the turn.

== Choose a stance

Stances represent an outward impression of commitment to a particular action.
To choose a stance, select a number between zero and your current energy corresponding to one type of action.


* If you choose a move corresponding to your stance and win, you keep the energy you committed. Your opponent will lose an amount equal to the energy you committed times a multiplier associated with your move.
* If you choose a move corresponding to your stance and lose, you will lose the energy you committed, but it is not multiplied.
* If you choose a different move, the stance was a feint, and has no effect on either side's losses. You did not commit the energy, you keep it, although it may still be reduced by other losses.

For remote games, or if you prefer cards, use cards indicating the type and amount.  Use cards marked zero to indicate no stance.

For local games, another option is to use small wooden cubes in 3 colors to track your energy, light for defend, dark for attack, and contrasting for grapple.
Remaining energy is public information, but conceal your total amount while selecting cubes so that you do not give away your choice before revealing.
Hold out an unambiguous fist containing selected cubes, then open your hand once both sides are ready to reveal.
Use an empty fist to indicate no stance.

.Example of choosing a stance
****
You have 3 remaining energy in ⬟, and choose 2 ⬟ for your stance.

* If you play a ⬟ move and win, your opponent will lose energy equal to 2 times a multiplier.
* If you play a ⬟ move and lose, you will lose the 2 ⬟ energy.
* If you play a ◯ or ▧ move, your stance will not affect losses to either side, but your 3 remaining ⬟ energy may be reduced by other losses. 
****

== Choose a move

Your most important move is surrender. If you play surrender, you are out of the conflict, and will eventually take your side's consequences of winning or losing the overall conflict, but do not suffer any energy losses for this turn. Surrender is not retreat; if you surrender in a lethal conflict your opponent can choose to kill your character immediately. If for some reason you have no other remaining moves, you must play surrender.

Other moves are defined by the name you chose, an action, an element, a base energy loss your opponent will suffer if you win, and a multiplier applied to the amount of stance energy you committed.

<<<
include::moves.adoc[]

When choosing a move, it is important to consider your potential disadvantage and combos.

== Disadvantage

If you lost your prior turn, and then play a move that matches the action *or* the element of your most recent losing move, it is at a disadvantage. If you lose, you will lose additional energy; you will also lose what otherwise would have been a tie.

Energy losses from disadvantage are cumulative with consecutive disadvantaged turns, at one point of energy per prior turn.
Disadvantage ends once you end a turn without losing, play a move that doesn't match, or at the end of the conflict.
It does not end once someone else is selected as an opponent, so leave your played move cards out face up to indicate disadvantage.
This does restrict your available moves.

.Example disadvantage
****
The prior turn you played ⬟ ☷ and lost, so that card is face up in front of you.
You play ◯ ☷, which contains ☷, so it is at disadvantage. You lose, and lose an additional point of energy. You keep ⬟ ☷ and ◯ ☷ face up in front of you.

The next turn, you play ⬟ ☲, which does not match ◯ ☷, so it is not at disadvantage. You lose, but do not lose additional energy from disadvantage. You keep ⬟ ☲ face up in front of you, and return ⬟ ☷ and ◯ ☷ to your available moves.
****

== Combos

Combos are relationships between moves, that are learned separately from moves.
Combos consist of a starting move and up to two options for followup moves.
If the immediately prior turn was a loss for your opponent, you can play any combo you know that follows from the move that won.
Combos do not affect ties, but if you play a move that combos and win, your opponent will lose additional energy.

Combo bonuses are cumulative with consecutive combo turns, at one point of energy per prior combo turn.
Leave your played cards out face up in front of your opponent to indicate a combo.
This does restrict your available moves.
A player can voluntarily end the combo before choosing a move in order to return all the moves to availability.
Combos end once you lose a turn, play a move that doesn't combo, choose a different opponent, or at the end of the conflict.

You can play up to 3 consecutive winning turns to continue a combo, then must pass.
This counts as one turn for purposes of players taking equal number of turns.
The character you pass to can continue the combo against the same opponent if possible.

.Example combo
****
You have played 2 consecutive winning turns, ⬟ ☷ then ▧ ☲.
Your possible combo followups from ▧ ☲ are ◯ ☲ or ⬟ ☲.  You play ⬟ ☲ and win. Your opponent loses an additional 2 points of energy.
Leave ⬟ ☷, ▧ ☲ and ⬟ ☲  face up in front of your opponent. You have played 3 consecutive turns, so you pass to another player on your side. If they know a followup to ⬟ ☲, they can continue the combo.
****

[NOTE]
====
Keep your face-up disadvantage cards closer to you than the cards for combos being played against you. Because combos end as soon as a different opponent is chosen but disadvantage does not, it should be clear from context which is which.
====

== Identify the winner

Check in order:

. If a move's action beats the other move's action, it wins.
. If a move's element beats the other move's element, it wins.
. If one move is disadvantaged, it loses.
. Otherwise it's a tie.

.Example winner
****
* You play ⬟ ☲, your opponent plays ▧ ☷. ⬟ beats ▧, you win.
* You play ⬟ ☲, your opponent plays ⬟ ☷. ☷ beats ☲, you lose.
* You lost your prior turn with a ◯ ☲, your opponent won their prior turn. You play ⬟ ☲ at disadvantage, your opponent plays ⬟ ☲, you lose.
****

== Resolve the consequences

In a tie, each character loses energy equal to the base amount for the other character's move, but no additional losses.
Ties end combos and disadvantage.

.Example consequences of tie
****
You play ⬟ ☲, your opponent plays ⬟ ☲. Neither of you were at disadvantage, so it's a tie. You each lose 3 energy. No cards remain face up to indicate combo or disadvantage.
****

If you played the winning move, the opponent loses energy equal to the sum of:

* (your committed stance energy times the multiplier of your move)
* their committed stance energy, without a multiplier
* the base amount of your move
* one point per prior win in your successful combo
* one point per prior loss in their disadvantage

When you commit stance energy and lose, that portion of the loss comes from the type you committed. For remaining losses, the person controlling the character that lost energy decides how to distribute it among the different types.

.Example consequences of a win
****
You won the prior turn, your opponent is at disadvantage with ⬟ ☷, and your combo followups are ▧ ☰ and ▧ ☯. You choose 2 ▧ for your stance, your opponent chooses 1 ◯ . You choose ▧ ☰ for your move, your opponent chooses ◯ ☷. Since ▧ beats ◯, you win. Your opponent loses a total of 13 energy:

* 2 times 3 from your stance
* 1 from their stance
* 4 from the base amount of your move
* 1 from your combo
* 1 from their disadvantage

At least 1 point of those losses is applied to ◯ and the remainder according to your opponent's choice.
****

If you reach zero energy for one action type, mark it for purposes of <<levelup.adoc#levelup>>.

If you reach zero energy in all action types, you are out of the conflict, and suffer the specified consequence.
In particular, if it is a lethal conflict, your character is dead, even if your side wins the overall conflict.
